nginx:
  - name: rabbitmq
    controler:
      _default: internal
    proxy_body_size:
      _default: "100m"
    domain:
      _default: "api-{{ $.Release.Namespace }}.xxx.ru"
      production: "api-rabbitmq.xxx.ru"
      aws-production: "api-rabbitmq.xxx.com"
    service:
      name: rabbitmq
      port: http-app
    
rabbitmq:
  image:
    _default: "rabbitmq:3-management-alpine" #collection
  pv:
    storageclass:
      _default: network-ssd # env
      aws-production: gp2 # ecr on AWS
    size:
      _default: 10Gi # env
  resources:
    cpu:
      requests:
        _default: 500m # env
    memory:
      requests:
        _default: 2000Mi # env
      limits:
        _default: 4000Mi # env